Configurando Slick
rodriggochaves/cicroom2api pull request #1
Opened 2017-11-13 17:18 UTC by rodriggochaves

A API consegue receber uma requisição `/api/users/` com 

```
{
	"username": "rodrigo", 
	"email": "rodrigo@email.com",
	"password": "password"
}
```

e responde:

```
{
    "status": "ok"
}

2017-11-14 14:31 UTC, soutokevin requested changes

2017-11-14 14:31 UTC, soutokevin commented on src/main/scala/com/cicroomapi/controllers/UsersController.scala
> +    UserModel.create(parameters("user").listParams)
isso não cria imediatamente o usuário e retorna uma future para isso

2017-11-14 14:31 UTC, soutokevin commented on src/main/scala/com/cicroomapi/controllers/UsersController.scala
> +    Response("ok")
A api retorna "ok" independentemente do resultado da future, que foi descartado

2017-11-17 22:21 UTC, rodriggochaves commented
Adiciona uma resposta assincrona usando o `AsyncResult` do Akka e usando o `.fold` em cima da `Future` do Slick. Da uma olhada para ver se isso resolve o problema.

2017-11-17 23:45 UTC, diogoqds approved these changes

2017-11-18 00:36 UTC, soutokevin approved these changes

2017-11-18 00:36 UTC, merged